### ISSUE TITLE
Issue with CSS compiling when running grunt dist

### ISSUE THREAD

**Issue by kimmobrunfeldt** [jlong/sass-bootstrap-defunct#102]
After cloning the repository, installing grunt-cli globally and "npm install", running "grunt dist" outputs:

```
Running "clean:dist" (clean) task

Running "recess:bootstrap" (recess) task

GENERAL USE: $ recess [path] [options]

OPTIONS:
  --compile
  --compress
  --config
  --format
  --includePath
  --noIDs
  --noJSPrefix
  --noOverqualifying
  --noSummary
  --noUnderscores
  --noUniversalSelectors
  --prefixWhitespace
  --strictPropertyOrder
  --stripColors
  --watch
  --zeroUnits
  --inlineImages

EXAMPLE:

  $ recess ./bootstrap.css --noIDs false

GENERAL HELP: http://git.io/recess
```

To sum up, CSS compiling does not work.

Recess version:

```
➜  sass-bootstrap git:(master) ✗ recess --version
1.1.9
```

**Comment by alademann** [comment]
@kimmobrunfeldt I have grunt commands working in my sass-bootstrap repo... although I choose to use compass instead of just "stock" sass to compile.  I'm sure you could adapt it for use with grunt-contrib-sass. 

[Here's my gruntfile](https://github.com/alademann/sass-bootstrap/blob/master/Gruntfile.js)

Hope that helps.

**Comment by Jehu** [comment]
Same problem here first (downloded zip instead of cloning). 

Then i do this steps to get it work:
- git clone ... ./bootstrap
- cd ./bootstrap
- npm install
- bundle install

After that i can run grunt dist without any problems.

**Comment by saalmaan** [comment]
I am also experiencing the same problem.

git clone git://github.com/jlong/sass-bootstrap.git ./bootstrap
cd ./bootstrap
npm install
bundle install
grunt dist

and when I type following command 'grunt dist' I get exact same error as mentioned in the first comment

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
