### ISSUE TITLE
Issue's including responsive CSS with bootstrap

### ISSUE THREAD

**Issue by derek-adair** [jlong/sass-bootstrap-defunct#104]
Sorry for the rookie question, but i'm a bit new to yo and scss in general...

I would like to use the responsive version of bootstrap, so i tried modifying my main.scss file and include @ import "bootstrap-sass/lib/responsive"; after @ import "bootstrap-sass/lib/bootstrap"; but it doesn't seem to work.

**Comment by rdandnayak** [comment]
According to my understanding of issue. Solution might be to Import  "bootstrap-sass/lib/responsive" directly in main.scss.
It won't work if you import it in  "bootstrap-sass/lib/bootstrap" & then import same to main.scss.

**Comment by AJ-Acevedo** [comment]
Checkout how I import bootstrap with jekyll.
This should get you going.
https://github.com/Synculus/jekyllkb/blob/master/_assets/stylesheets/application.scss

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
