### ISSUE TITLE
separate mixins

### ISSUE THREAD

**Issue by hd-deman** [jlong/sass-bootstrap-defunct#111]
why not to separate mixins like this:

```
lib/mixins/button-variant.scss
lib/mixins/box-shadow.scss
...
```

each mixin in one file, so we can easy replace mixins.

**Comment by AJ-Acevedo** [comment]
I think this issue should be closed as a 'wont-fix' as sass-bootstrap is a 1:1 translation from bootstrap Less to Sass.

@hd-deman This might be better asked on the twbs/bootstrap repo.
