### ISSUE TITLE
_navs.scss causes infinite loop and memory error when compiled

### ISSUE THREAD

**Issue by evantishuk** [jlong/sass-bootstrap-defunct#113]
I am using sass-bootstrap with with leafo/sccsphp and it appears to be breaking when including _navs.scss:

After some debugging, I've tracked it down to https://github.com/jlong/sass-bootstrap/blob/master/lib/_navs.scss#L104.  Looks like extending a class with the same name as the current class causes an infinite loop:

```
&.nav-justified {
    @extend .nav-justified;
```

Not sure if this _should_ compile and is thus an error within scssphp or if it's a bug on this end.

I know it's usually a faux pas to reference an error triggered by another library, but I figured I'd float it out here first since a fix would likely be easier from here. If it looks like an error more applicable to scssphp, then I'll kick it over there.

FWIW, I just commented line 104 to stop the breakage and it doesn't appear to impact anything.

**Comment by jlong** [comment]
Sounds like a difference in implementations. File an issue with the scssphp project, but I will happily accept a pull request that fixes this in this project for the time being.

**Comment by evantishuk** [comment]
Well, you know, I should be flogged.

Looks like there's an issue reported from 2-months ago on this exact same issue: https://github.com/leafo/scssphp/pull/113 -- with the same example breakage.

Sorry about polluting your issue log.

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
