### ISSUE TITLE
Compiling with libsass fails

### ISSUE THREAD

**Issue by dchest** [jlong/sass-bootstrap-defunct#117]
After updating to 3.0.1, here's the error I'm getting from sassc (libsass):

`/assets/scss/bootstrap/mixins:712: error: invalid selector after ,`

Any ideas on what might be wrong? Thanks!

**Comment by ain** [comment]
For the record: I've filed a corresponding issue [#182 for libsass](https://github.com/hcatlin/libsass/issues/182). You're welcome to add some additional info there.

For sass-bootstrap I guess the issue can be closed?

**Comment by dchest** [comment]
@ain thanks, closing here.

**Comment by dchest** [comment]
Opening again, see https://github.com/hcatlin/libsass/issues/182
