### ISSUE TITLE
Packagist.org still show old composer name

### ISSUE THREAD

**Issue by christianjul** [jlong/sass-bootstrap-defunct#122]
Packagist.org needs to be updated to reflect the name change in the composer manifest. it could break code that relies on install path and composer-name being in sync. Also it is not possilble to install under the name.

**Comment by greg0ire** [comment]
What about versions older than 3.0.1 ? Shouldn't we re-submit it as a new package rather than try to rename the old one (which does not seem possible, btw)?

**Comment by christianjul** [comment]
I am not sure how well packagist/compsoier handles renaming Using a replace declaration, might solve it http://getcomposer.org/doc/04-schema.md#replace

**Comment by greg0ire** [comment]
Could be useful, but in rares cases: If your project requires package A, which requires old-name, then you will be able to have new-name even if you can't edit package A's composer.json . You can do this in a PR, it will not harm. 

From the doc : 

> Note that you should not rename the package unless you really intend to fork it in the long term, and completely move away from the original package. Composer will correctly pick your package over the original one since the custom repository has priority over packagist. If you want to rename the package, you should do so in the default (often master) branch and not in a feature branch, since the package name is taken from the default branch.
> 
> If other dependencies rely on the package you forked, it is possible to inline-alias it so that it matches a constraint that it otherwise would not. For more information see the aliases article.

How do you understand this ?

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
