### ISSUE TITLE
Why does the Gruntfile use Less?

### ISSUE THREAD

**Issue by grayxr** [jlong/sass-bootstrap-defunct#127]
I was wondering why the Gruntfile is setup to compile Less files and not the Sass files - this is a Sass version of bootstrap, so shouldn't the Gruntfile use a Sass compiler?

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
