### ISSUE TITLE
bower ECMDERR  exit code #69

### ISSUE THREAD

**Issue by Blumed** [jlong/sass-bootstrap-defunct#129]
I am trying to use Yeoman, and bootstrap isn't loading because of bower. When I try to install the package: bower install sass-bootstrap-compass

Search results:

```
sass-bootstrap git://github.com/jlong/sass-bootstrap.git
sass-bootstrap-compass git://github.com/alademann/sass-bootstrap.git
sass-bootstrap-glyphicons git://github.com/greaterweb/sass-bootstrap-glyphicons.git
chosen-sass-bootstrap git://github.com/joeylomanto/chosen-sass-bootstrap.git
```

$ bower install sass-bootstrap-compass
bower not-cached    git://github.com/jlong/sass-bootstrap.git#~3.0.0
bower resolve       git://github.com/jlong/sass-bootstrap.git#~3.0.0
bower not-cached    git://github.com/Modernizr/Modernizr.git#~2.6.2
bower resolve       git://github.com/Modernizr/Modernizr.git#~2.6.2
bower not-cached    git://github.com/components/jquery.git#~1.10.2
bower resolve       git://github.com/components/jquery.git#~1.10.2
bower not-cached    git://github.com/alademann/sass-bootstrap.git#*
bower resolve       git://github.com/alademann/sass-bootstrap.git#*
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/components/jquery.git", exit code of #69

Additional error details:
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

when I try running sudo I get this:
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option

I have done so with no luck. I am not sure how to fix this, but I would love a hand. Thanks in advance.
- C

**Comment by jeremyadavis** [comment]
Had similar issue with the Xcode/iOS license when starting a new yo project after I upgraded to Mavericks.

Had to run **sudo xcodebuild -license** then agree to it at the bottom. 

Everything worked then.

**Comment by isnoozzze** [comment]
thank you.

**Comment by BetterCasper** [comment]
Thanks a lot!

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass

**Comment by komunamu** [comment]
Thanks a lot!

**Comment by mrbmc** [comment]
Thank you :+1:

**Comment by yuzima** [comment]
It works, thank u very much

**Comment by nigelalford** [comment]
"Had to run **sudo xcodebuild -license** then agree to it at the bottom."

Worked for me too.

**Comment by dehviana** [comment]
thanks man

**Comment by Blumed** [comment]
I figured out a work around. Sorry I forgot to post it. Thanks @jeremyadavis for stepping in. 

+1

**Comment by kirpheaice** [comment]
Thank you very much~

**Comment by tuannguyenminh2086** [comment]
thank a lot!!!

**Comment by devolkpl** [comment]
Whaaaat? o.O  Thanks man!

**Comment by yasir095** [comment]
thanks, worked

**Comment by AdonLee** [comment]
thanks

**Comment by erdemildiz** [comment]
thanks man, Its worked :+1:

**Comment by indieocean** [comment]
Thanks! A+

**Comment by jonathanmccormick** [comment]
"Had to run sudo xcodebuild -license then agree to it at the bottom."

Fixed the issue for me too. Thanks jeremyadavis!

**Comment by jguix** [comment]
Worked for me, thanks!

**Comment by ghost** [comment]
It worked also for git issue in mac
