### ISSUE TITLE
More files to be ignored in bower.json

### ISSUE THREAD

**Issue by fabarea** [jlong/sass-bootstrap-defunct#131]
Can I suggest adding more files to be ignored in bower.json likewise in the upstream repository https://github.com/twbs/bootstrap/blob/master/bower.json. This would be convenient when deploying with bower not having so many "meta" files.

**Comment by jlong** [comment]
You'd need to suggest this in the upstream repo. We don't add features to bootstrap. We just convert it from Less to Sass.

**Comment by fabarea** [comment]
The link provided above **is** from the upstream repo. Actually, file `bower.json` could be simply synchronized as such.

**Comment by jlong** [comment]
I see... you meant _like_ the upstream repo. Sounds like a good idea! Would you mind sending in a pull request?
