### ISSUE TITLE
Add .container-fluid variation for full-width containers and layouts

### ISSUE THREAD

**Issue by ghost** [jlong/sass-bootstrap-defunct#132]
Bootstrap recently added .container-fluid class. It would be great if this sass fork can update.

Reference:
https://github.com/twbs/bootstrap/commit/6273604601c58284f49b38ae4e52533b9689437c

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
