### ISSUE TITLE
bower sass-bootstrap syntax error in yeoman

### ISSUE THREAD

**Issue by matthewfowles** [jlong/sass-bootstrap-defunct#134]
Hi 

I get this error when running grunt serve in yeoman.

```
error app/styles/main.scss (Line 121 of app/bower_components/sass-bootstrap/lib/_mixins.scss: Invalid CSS after "...-shadow($shadow": expected ")", was "...) {")
```

I have updated all packages and uninstalled and re-installed everything. Really at a loss as how to fix.

Any help?

Thanks

**Comment by danielseidl** [comment]
hey, same here - (how) did you fix it?

**Comment by danielseidl** [comment]
update: this has helped me:

gem install sass 
gem install compass

http://www.beequeue.co.uk/2014/01/28/yeoman-angular-bootstrap-sass-compilation-error/

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
