### ISSUE TITLE
Fixed Nav Bar Showing scroll bar when it veiwed in lg - Not same as non-sass bootstrap

### ISSUE THREAD

**Issue by amitgoswami7** [jlong/sass-bootstrap-defunct#140]
OS: Desktop Windows Vista 32-bit
Browser : Chrome Version 32.0.1700.76 m 
Browser : Firefox Version 26.0

SITE TO BE CHECKED : http://sassbs-navbar-scroll.appspot.com/

Procedure to reproduce : 
1. Load Site.
2. Reduce Browser width so that nav bar buttons collapse.
3. Click Nav button to show drop down links.
4. Scroll using mouse wheel on the Nav Bar Drop Down. (Dont Click on any link)
5. Enlarge the Browser width.
6. Mouse over to the Nav Bar.
7. Scroll using mouse wheel.

Expected Behavior:
Using no sass port.
![bootstrap_fixed-nav-bar_scroll-bar_innav_lg_chrome_correct](https://f.cloud.github.com/assets/4773380/1957557/f9fda276-820a-11e3-981e-ddfdc2323121.jpg)

I have just replaced 2 files Script and the css to pull from examples of bootstrap. Please check comment of  Changed-amitgoswami7 to see my changes.
You can toggle between normal bootstrap and sass-bootstrap.

Error Behavior:
Using sass port:
![sass_bootstrap_fixed-nav-bar_scroll-bar_innav_lg_chrome](https://f.cloud.github.com/assets/4773380/1957574/78b35958-820b-11e3-8f27-2d4fd2d75382.jpg)

![sass_bootstrap_fixed-nav-bar_scroll-bar_innav_lg_chrome_2](https://f.cloud.github.com/assets/4773380/1957576/803c47de-820b-11e3-8052-af7813984769.jpg)

Original Issue Site Still under development : http://amitgoswami7-profile.appspot.com/

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
