### ISSUE TITLE
make-row setting incorrect margins

### ISSUE THREAD

**Issue by onwsk8r** [jlong/sass-bootstrap-defunct#141]
Lines 664-665 of _mixins.scss read:
  margin-left: ($grid-gutter-width / 2);
  margin-right: ($grid-gutter-width / 2);

Should be
  margin-left: ($grid-gutter-width / -2);
  margin-right: ($grid-gutter-width / -2);

To set negative margin on rows

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
