### ISSUE TITLE
Official TWBS sass handover

### ISSUE THREAD

**Issue by eddiemonge** [jlong/sass-bootstrap-defunct#143]
Any plans to give the `sass-bootstrap` and `bootstrap-sass` names in Bower to the Bootstrap project so they don't have to have a silly name like `bootstrap-sass-official`?

**Comment by MichaelSp** [comment]
+1

**Comment by jlong** [comment]
I'm fine with that. How do we make it happen?

**Comment by eddiemonge** [comment]
cc :/ @ sindresorhus

**Comment by glebm** [comment]
@jlong You can now do it with:

``` bash
curl -X DELETE "https://bower.herokuapp.com/packages/bootstrap-sass?auth_token=GITHUB_TOKEN"
```

You can get the token from: https://github.com/settings/applications#personal-access-tokens

**Comment by edouard-lopez** [comment]
Any progress here ? The `bower`package is [available under two different names](http://bower.io/search/?q=bootstrap-sass): 
- `bootstrap-sass-twbs` Official Sass port of Bootstrap
- `bootstrap-sass-official` Official Sass port of Bootstrap

**Comment by mvanroon** [comment]
+1

**Comment by BeMrTeal** [comment]
+1

**Comment by kenips** [comment]
:+1: please!

**Comment by jlong** [comment]
@glebm I ran the commands, but it says I must be a collaborator?

> Must be a collaborator on GitHub.com repository

**Comment by kenips** [comment]
Hey @jlong thanks for looking into this! I think it fails because you have changed your repo name so the registered URL no longer works. Try changing it back to sass-bootstrap and try again.

**Comment by jlong** [comment]
@kenips I tried that and it failed as well!

**Comment by jlong** [comment]
Happy to add anyone as a collaborator if they want to figure this out.

**Comment by mdo** [comment]
@glebm @jlong How can I help?

**Comment by kenips** [comment]
@jlong I haven't heard anything back yet, but happy to take a look as a collaborator. I notice that the URL https://github.com/jlong/sass-bootstrap is still not working (redirecting to defunct). Has it been renamed?

**Comment by jlong** [comment]
@kenips added you as a collaborator.

Yup. The repo was renamed to make it easy to see that it should not be used any more. I'll change it back for the time being.

**Comment by kenips** [comment]
@jlong no luck. One more try - could you rename to `sass-twitter-bootstrap`? That's the original registered name actually.

**Comment by jlong** [comment]
@kenips done.

**Comment by kenips** [comment]
and it worked! @mdo it's yours now!

**Comment by jlong** [comment]
Thanks @kenips!

**Comment by desandro** [comment]
Hi there. Let me know if I can help with any Bower unregistrations.

**Comment by kenips** [comment]
hey @desandro thanks for checking in! We figured it out in the end so it's done. Now it's just up to twbs to pick up `bootstrap-sass` :)

**Comment by Shipow** [comment]
Sorry for re opening this but I think it would be helpful to give some details about the 'how' for everybody who followed the thread. Thank you very much.

**Comment by kenips** [comment]
Right, it's actually just a naming problem. The name was registered under `jlong/sass-twitter-bootstrap` so the error was simply that it did not exist. We temporarily renamed this repo back to `sass-twitter-bootstrap` and it worked.
