### ISSUE TITLE
Riddled with errors.

### ISSUE THREAD

**Issue by KingScooty** [jlong/sass-bootstrap-defunct#40]
Guys, this project is riddled with errors.
Mixins are failing pretty hard. I'm getting alot of these errors:

`Syntax error: Mixin transition takes 1 argument but 2 were passed.`

**Comment by m5o** [comment]
Please update to sass 3.2+

**Comment by KingScooty** [comment]
I'm using version 3.2.3.

You might want to check the mixins file:

`@mixin box-shadow($shadow...) {`

**Comment by wyne** [comment]
That is valid syntax:
http://sass-lang.com/docs/yardoc/file.SASS_REFERENCE.html#variable_arguments

It was added in this pull request: https://github.com/jlong/sass-twitter-bootstrap/pull/33

Does it still not compile?
