### ISSUE TITLE
Tag versions for bower

### ISSUE THREAD

**Issue by inukshuk** [jlong/sass-bootstrap-defunct#41]
It seems that [bower depends on git tags for versioning](https://groups.google.com/forum/?fromgroups=#!topic/twitter-bower/SvhIMBNalw0) – currently, the component.json is for version 2.2.1 but bower does not pick that up; I guess you need to add v2.2.1 git tag in order for bower to be able to install the current version.

**Comment by m5o** [comment]
Thanks for the notice. I've added the tag

**Comment by inukshuk** [comment]
As a quick follow-up, can you tell me what the current bower workflow is? For instance, I would like the bower component to pick up the latest bugfixes (e.g., #55) – however, since the version number follows the bootstrap release (I assume) you can't really issue patch releases (unless calling them something like 2.3.0.1).

In a regular library of course you wouldn't push a new release for every bugfix, but since bootstrap-sass should be essentially identical to the equivalent bootstrap release I think it would make sense to re-apply the version tag for bower to pick up the latest bugfixes for the current release – what do you think?

I am aware that this wouldn't be practical if you wanted to support and maintain multiple released versions, but in a case like this it seems to me this wouldn't hurt. I know this sounds like a chore, but what do you think?

**Comment by sindresorhus** [comment]
Bower follows semver as any other Node module. http://semver.org/

You can use build notation if you don't want to bump the patch version

> A build version MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch version or pre-release version. Identifiers MUST be comprised of only ASCII alphanumerics and dash [0-9A-Za-z-]. Build versions satisfy and have a higher precedence than the associated normal version. Examples: 1.0.0+build.1, 1.3.7+build.11.e0f985a.

**Comment by inukshuk** [comment]
@sindresorhus thanks! A build version tag would solve the issue perfectly.
