### ISSUE TITLE
carousel white space (only right side) on iPhone 5 

### ISSUE THREAD

**Issue by Jacubeit** [jlong/sass-bootstrap-defunct#46]
Hi,

thanks for the great work! I just built my first rails app using Bootstrap carousel.

If i visit the page with my iPhone 5 i have a white space on the right side of the carousel. The same behavior when visiting 

http://twitter.github.com/bootstrap/examples/carousel.html

Is there anyway I can fix this? 

If you want to see for yourself:

http://swimcy.com

Thank you very much!

Joh

**Comment by m5o** [comment]
please file a bugreport on the upstream Project. Thanks
