### ISSUE TITLE
Please indicate which version of the sass spec is used

### ISSUE THREAD

**Issue by greg0ire** [jlong/sass-bootstrap-defunct#50]
I tried compiling sass-twitter-bootstrap with https://github.com/leafo/scssphp , but it doesn't work because of the usage of this kind of syntax:

``` sass
@mixin test($color, $textShadow: 0 -1px 0 rgba(0,0,0,.25)) {
  border-color: darken($color, 15%);
}
```

The default argument for $textShadow makes the compiler fail. I guess this must be a new feature.

**Comment by GaryJones** [comment]
> I guess this must be a new feature.

Would it not be worth you ensuring you're using the latest version of Sass, before reporting a bug like this?

**Comment by greg0ire** [comment]
That's the problem, I'm not using sass. I use the latest version of scssphp, which implements SCSS 3.1.20 . I'm not suggesting that you fix what I think is not a bug at all. I'm suggesting that you warn users in your README, like this

> We are using SCSS x.y.z syntax

**Comment by GaryJones** [comment]
This isn't my project, but a fair enough comment. As the majority of folks would be able to update to the latest release fairly easily, it's sensible to assume that this and other Sass projects may rely on the latest version being available. It's up to the project owner to decide if a comment on the readme is needed (one more thing to maintain), but you should nudge the scssphp project can be bumped to the latest version, if you've not already.

**Comment by greg0ire** [comment]
They clearly state that they implement 3.1.20 on their homepage, so I assumed they are not planning to bump to the latest version soon and moved on to sass 3.2.5 . I think you could either say that the latest version of sass is required, or list sass installations known to work well with sass-twitter-bootstrap .

**Comment by robocoder** [comment]
Is this moot?  The latest scssphp code takes this:

```
@mixin test($color, $textShadow: 0 -1px 0 rgba(0,0,0,.25)) {
  border-color: darken($color, 15%);
  text-shadow: $textShadow;
}

div {
    @include test(red);
}
```

and outputs:

```
div {
  border-color: #b30000;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, .25); }
```

**Comment by dev-mraj** [comment]
i am using ruby sass, any set my env to compile sass on local and no compilation on server,
 and i test your code, its working fine, you sholud also test it with latest version of sass in ruby,

**Comment by greg0ire** [comment]
Ok, I guess I did something wrong then.

**Comment by Flask** [comment]
I have to agree with greg0ire. In my case it was a bit of a pain, to figure out which tag is compatible to e.g. sass v3.1.19.
@GaryJones Indeed I'm able to use the latest version on my local dev environment, but when it comes to my prod environment, I'm not willing to install make-utils as gcc etc. Especially for people using debian or debian based systems its pretty hard to get an up-to-date version of sass.
