### ISSUE TITLE
Update jQuery?

### ISSUE THREAD

**Issue by rschmitty** [jlong/sass-bootstrap-defunct#59]
Would it be possible to upgrade the jQuery dependency in [component.json](https://github.com/jlong/sass-twitter-bootstrap/blob/master/component.json) to 1.9?

The official Bootstrap 2.3 has [upgraded to jQuery 1.9](http://blog.getbootstrap.com/2013/02/07/bootstrap-2-3-released/)

When using Bower to install the user receives a warning

```
Please note that
    your-webapp requires jquery ~1.9.1
    sass-bootstrap requires jquery ~1.8.0

Resolved to jquery v1.9.1, which matches the requirement defined in the project's component.json.
Conflicts may occur.
```

No harm comes of this but would be nice to clean up the warning

**Comment by roverwolf** [comment]
Although the documentation mentions upgrading to jQuery 1.9, only the included  js/tests/vendor/jquery.js file was upgraded (and has also been upgraded in sass-twitter-bootstrap).

Both the [2.3.1](https://github.com/twitter/bootstrap/blob/v2.3.1/component.json) and [master](https://github.com/twitter/bootstrap/blob/3469339068a5676b225af7a39dffcad41e391934/component.json) versions of component.json in the upstream library still use ~1.8.0 as the jquery dependency.

**Comment by rschmitty** [comment]
Ha, how bout that.  Thanks for pointing that out
