### ISSUE TITLE
Use it into openframework (D7)

### ISSUE THREAD

**Issue by webmasterpf** [jlong/sass-bootstrap-defunct#70]
Hi

I would to know how can i replace the less version (used by openframework: https://github.com/SU-SWS/open_framework) by the sass version, and having a code example to use span like intead of adding classes to my tpl file.It would be something like : 
.my-classes{ @include span4;}

thanks for tips

**Comment by m5o** [comment]
Sorry, but this is not related to any issues with this fork.
