### ISSUE TITLE
sass-twitter-boostrap in Sass instead of Scss

### ISSUE THREAD

**Issue by ryanburnette** [jlong/sass-bootstrap-defunct#75]
Hey guys. I probably haven't spent enough time looking for an answer, but I actually want to use the sass-twitter-bootstrap in the Sass syntax instead of Scss.

I tried sass-convert but it broke most or all of the files because of how the comments are formatted. It looks like sass-convert doesn't deal with `/* comment */` on one line after code.

Has anyone else accomplished using this with Sass instead of Scss?

![sass](https://f.cloud.github.com/assets/2252601/569318/b66957d2-c6fb-11e2-8455-e87fd96b6328.png)
![scss](https://f.cloud.github.com/assets/2252601/569319/b66a1834-c6fb-11e2-856a-fe3f3de18347.png)

**Comment by jlong** [comment]
That's a pity that sass-conver doesn't handle these comments well. It would probably be good to file an issue on the Sass project.

What's your motivation for wanting bootstrap in the Sass syntax? Sass understands both syntaxes.

--John

**Comment by ryanburnette** [comment]
I think sass-convert is its own thing. I'm going to see if I can submit an issue about it specifically.

I thought the Sass compiler would freak out if I gave it a mix of files in both syntaxes. The last time I tried that it didn't appear capable of handling such. So I tried to convert over to all Sass syntax for that reason. I'll revisit the prospect of having a project mixed across the two syntaxes.

The core motivation is that I want to write in Sass instead of Scss on my next project.

**Comment by ryanburnette** [comment]
Also it looks like the issue already has a pull request waiting to solve it.
https://github.com/nex3/sass/pull/713

**Comment by jlong** [comment]
Sass should be fine with mixing syntaxes. We do it at work and it compiles nicely.

If your desire is to layer your styles on top of bootstrap you might want to leave boostrap as is and just create a "bootstrap-overrides.sass" file with your modifications. This might be the simplest way to use bootstrap and keep it updated as improvements are released.

If you really want to fork the project I'm afraid you are probably on your own. At least until sass-convert is updated.

--John

**Comment by ryanburnette** [comment]
Thanks, @jlong, for the quick response. This only appeared to be an issue to me based on my misunderstanding that mixing syntaxes would break the compiler. I asked this question to an expert at a conference and was told it wasn't possible. That was a couple years ago. I suspect that the answer was as wrong then as it is now. ;) I just tested and it's working great.

I always make a `bootstrap/` and `bootstrap-modified/` folder in addition to my own `project/` folder so I can quickly update the core on all my projects.

I'll also take this opportunity to say how much I appreciate this project. I literally use it every day. I really love Bootstrap. Being a Sass user, however, I would have never adopted it without you and the other contributors' help. I hope one day I can pay it back or contribute to the project.

**Comment by jlong** [comment]
Glad that you found a good solution!

**Comment by ryanburnette** [comment]
@jlong Apparently the problem I had was just a problem with the Sass syntax highlighting I'm using in Sublime Text 2. :(
