### ISSUE TITLE
Row fluid mixin ?

### ISSUE THREAD

**Issue by webmasterpf** [jlong/sass-bootstrap-defunct#76]
Hi

How can i use the fluid layout with the sass version of TBS ?
Actually i test wgithout success :

```
.rowZone{
    //@include makeRow;
@include makeRowFluid; don't work
@include makeFluidRow; don't work
    @extend .row-fluid; no seem to work
}
```

thanks

**Comment by jlong** [comment]
What kind of error messages are you getting?

I believe what you want is something more like:

```
@import "path/to/bootstrap/grid";

.rowZone {
  @include makeRow;
  @extend .row-fluid;
}
```

**Comment by webmasterpf** [comment]
```
error sass/layout-home.scss (Line 43: Undefined mixin 'makeFluidRow'.)
```

my issue is more glable to RWD, because with the less version images resize themselves on mobile,and here not.So i would try the fluid layout but i don't know which mixin to use, as RowFluid or FluidRow doesn't exist.
Do your code is the way to use fluid layout ?
Globally does exist a kind of sheatsheet of mixin to use in TBS sass ?

thanks a lot

**Comment by jlong** [comment]
You can see all of the mixins that are available to you in the Sass version here:

https://github.com/jlong/sass-twitter-bootstrap/blob/master/lib/_mixins.scss

There is no `makeFluidRow` mixin. Is this part of the Less version? Perhaps we need to port it over.

Please try the code I posted.

**Comment by webmasterpf** [comment]
This mixin doesn't exist in original project.I  have read it in to post about another port of TBS to sass (T McDonald).
Your code doesn't cause error, but no change on mobile yet.
My goal is to replace TBS Less by Sass into a drupal sub-theme of https://github.com/SU-SWS/open_framework
This base theme provide an out of the box responsive resizing for images.I think this feature come from TBS,so i would find back it with the sass version..

OFW use this and i think it's an addition by them as a bootstrap override :

```
[class*="span"].clear-row{
    clear:both;
}
```

porting this to my project could be a good thing , unless the 

```
@mixin clearfix
```

can replace it.

**Comment by webmasterpf** [comment]
Your code push the content to the left...
Do exist a .show-grid class to debug layout ?
Do the @mixin grid-fluid-span could replace the makeRow mixin for fluid layout ? if yes how to use it ?

**Comment by jlong** [comment]
I'm not aware of a .show-grid class.

I've never used the grid layout stuff myself so I'm afraid I can't really provide support on this level. You might ask on the actual Bootstrap project and then find the necessary code in the Sass conversion.

--John

**Comment by webmasterpf** [comment]
Could you provide example of scss file and layout to show usage of mixins ? this is the most difficult actually to do.

**Comment by jlong** [comment]
Personally, I'd recommend using the class names that bootstrap provides. The mixins appear to be designed for generating the CSS bootstrap requires. Not so much for applying them to your own elements.

You could use `@extend` if you want to avoid applying multiple class names to an HTML element:

```
.myRow {
  @extend .row-fluid;
}
.mySpan {
  @extend .span1;
}
```

But honestly, it's more modular (and easier) to just use multiple class names in the HTML. The bootstrap documentation is very thorough:

http://twitter.github.io/bootstrap/scaffolding.html#gridSystem

**Comment by webmasterpf** [comment]
your code give me an idea, and i test this :

```
 .rowZone{
/*      @extend .row-fluid;*/
        @include makeRow;
   }
#logoHead{
  @include makeColumn(4);
 }
#navPicto{ 
/*    @include makeColumn(8);*/
    @extend [class*="span"];
    @extend span8;
}
```

this scss applied to :

```
<div id="header-haut" class="rowZone">
        <div id="logoHead"></div>       <!-- /#logo -->
     <div id="navPicto"></div>
   </div><!-- /rowZone -->
```

it seem to work and will test it on another rows...and see if image resizing work better with.But span8 isn't recognize as class and .row-fluid pull the second block downside the first one..
