### ISSUE TITLE
Can't compile with node-sass

### ISSUE THREAD

**Issue by georgiosd** [jlong/sass-bootstrap-defunct#81]
Any ideas why this happens?

> sass.renderSync({ file: 'C:\Users\Georgios\Desktop\foo\lib\bootstrap.scss', includePaths: [ 'C:\Users\Georgios
> \Desktop\foo\lib' ] });
> Error: C:\Users\Georgios\Desktop\foo\lib/_mixins.scss:383: error: error reading values after opacity

**Comment by declantraynor** [comment]
@georgiosd This is an issue in the underlying libsass code used by node-sass. Check out [this issue](https://github.com/hcatlin/libsass/issues/72) where @bitc offers a temporary workaround.
