### ISSUE TITLE
Mixin opacity (from compass) isn't compatible with the one used here

### ISSUE THREAD

**Issue by julien-c** [jlong/sass-bootstrap-defunct#82]
Which makes it hard to use sass-twitter-bootstrap as a part of a larger compass project.

Is there any way to work around this? Maybe change the semantics of this particular Bootstrap mixin?

Thanks!

**Comment by jlong** [comment]
Closing as there is now an official Sass Bootstrap port! Please add an issue there if this is still a problem: https://github.com/twbs/bootstrap-sass
