### ISSUE TITLE
Collapsed navbar missing .collapsing class for transition style

### ISSUE THREAD

**Issue by jkd77** [jlong/sass-bootstrap-defunct#86]
Please add the following to _component-animations.scss (at the end of the file):

.collapsing
{
  position: relative;
  height: 0;
  overflow: hidden;
  @include transition(height .35s ease);
}

Otherwise the closing of the navigation bar using the button displays the links too long. As in after the dropdown has already closed.

Thanks!

ps -> Thanks for the sass translation awesome sauce!

**Comment by m5o** [comment]
follow the latest commits in the 3.0.0-wip branch #73
