### ISSUE TITLE
Warning for @extend .form-inline in navbar.scss

### ISSUE THREAD

**Issue by jkd77** [jlong/sass-bootstrap-defunct#88]
WARNING on line 149 of _navbar.scss: ".navbar-form" failed to @extend ".form-inline".
  The selector ".form-inline" was not found.
  This will be an error in future releases of Sass.
  Use "@extend .form-inline !optional" if the extend should be able to fail.

Couldn't find this in previous issues. My bad if I missed something.

**Comment by tachun** [comment]
Just update the branch 3.0.0-wip, than I've this error message in navbar.scss:

DEPRECATION WARNING on line 263 of /sass-twitter-bootstrap/lib/_navbar.scss:
  @extending an outer selector from within @media is deprecated.
  You may only @extend selectors within the same directive.
  This will be an error in Sass 3.3.
  It can only work once @extend is supported natively in the browser.

**Comment by m5o** [comment]
due to a lot of changes in the last days we are currently not finished the transition to scss. still in the making...

btw. this is an deprecation warning no an error

**Comment by m5o** [comment]
These should be fixed
