### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by naillizard** [jlong/sass-bootstrap-defunct#89]
Hi guys,

I'm just trying to use this with a [Laravel 4](http://laravel.com/) project, using [LaravelGuard](https://github.com/JeffreyWay/Laravel-Guard) to watch/compile/minify the sass => css.

I have a application.scss and I'm trying to @import 'bootstrap'; but it fails because of compass...

any ideas how to get it sorted?

**Comment by sheabunge** [comment]
What do you mean 'it fails because of Compass'? it works for me when compiling through the Compass command line tool.

**Comment by naillizard** [comment]
Yes, it probably fails because I'm not compiling through the compass
command line, but using laravelguard to watch/compile.

I think it might be just a laravel-guard thing.

Sent from my iPhone

On 2/08/2013, at 7:05 PM, Shea Bunge notifications@github.com wrote:

What do you mean 'it fails because of Compass'? it works for me when
compiling through the Compass command line tool.

—
Reply to this email directly or view it on
GitHubhttps://github.com/jlong/sass-twitter-bootstrap/issues/89#issuecomment-21989723
.

**Comment by naillizard** [comment]
Bootstrap already imports compass... It should work fine if compiling
through the compass command line. Might load an issue up on laravel-guard
page.

Sent from my iPhone

On 3/08/2013, at 1:15 AM, Kevin Granger notifications@github.com wrote:

try to import compass first

@import https://github.com/import "compass"
@import https://github.com/import "bootstrap/variables"
@import https://github.com/import "bootstrap"
@import https://github.com/import "font-awesome"
...

—
Reply to this email directly or view it on
GitHubhttps://github.com/jlong/sass-twitter-bootstrap/issues/89#issuecomment-22004736
.

**Comment by jlong** [comment]
For the record this project does not use Compass. There are other versions of Bootstrap in Sass that do, but this one is focused on a one-to-one conversion.

**Comment by jlong** [comment]
What error message are you getting?

**Comment by naillizard** [comment]
Wasn't anything to do with this project, the problem was with Laravel Guard bundle, sorted now.
