### ISSUE TITLE
Form classes missing

### ISSUE THREAD

**Issue by Kaske** [jlong/sass-bootstrap-defunct#91]
There are some classes that exist in Bootstrap 3.0 like:

```
.form-control-static
```

but they are non-existing in the _forms.scss.

This file hasn’t been updated to the latest version.

**Comment by ryanburnette** [comment]
This project is on v2.3.2. Check the tags or the read me for the version. https://github.com/jlong/sass-twitter-bootstrap/releases

**Comment by m5o** [comment]
check out the 3.0.0-wip branch

**Comment by Kaske** [comment]
Got it, thanks.
