### ISSUE TITLE
How to override _variables.scss

### ISSUE THREAD

**Issue by naillizard** [jlong/sass-bootstrap-defunct#92]
Hi, trying to figure out a way to override _variables.scss.

Should I add a _bootstrap_overrides.scss with the overrides and import this file after

``` ruby
@import "variables";
@import "../../sass/bootstrap_overrides";
```

any better way to do this?

**Comment by jlong** [comment]
Variables declared in _variables.scss are declared with the !default directive, which means that if you set them beforehand, your values will be respected. So you can actually import your overrides before bootstrap.
