### ISSUE TITLE
Standalone project

### ISSUE THREAD

**Issue by AlexandreBroudin** [jlong/sass-bootstrap-defunct#93]
It would be more efficient to have this project as a standalone project.
It's a mess (git) if you want to work on the original Bootstrap (branches) and this one.

Just a suggestion

**Comment by jlong** [comment]
It's handy to show that this is a fork of the original project. What's motivating you to use both projects at the same time?

**Comment by AlexandreBroudin** [comment]
First, we can't fork a fork, and at the end, this project is different from the original one (structure, variables, etc.).
I wanted to contribute to the LESS project and this one, so, like i said, exept doing some git remote stuffs, its a bit tuff to work on both projects.

**Comment by jlong** [comment]
Is the problem that you are working on both projects in the same directory just switching branches to work on this one and back to work on the original? Or is it harder to apply patches for some reason?

**Comment by AlexandreBroudin** [comment]
Yes i'm working in the same directory but switching branches is not difficult at all.
But nevermind, it was just a suggestion, its just the gymastic of switching between 2 projects.
I think i will clone this one in a directory, and the LESS one in an other directory (for comparing files etc.)

**Comment by jlong** [comment]
Ah, yes. I'd recommend working in two directories. You should be able to generate a diff of your changes in one and apply it to the other with the patch command:

https://en.wikipedia.org/wiki/Patch_(Unix)

I know, not very idea, but it should work.

**Comment by AJ-Acevedo** [comment]
@ AlexandreBroudin Just create a GitHub Organization. This will allow you to fork both. Sass at your Organization and LESS on your personal account.

That's how I do it
https://github.com/AJAlabs/bootstrap
https://github.com/AJ-Acevedo/sass-twitter-bootstrap
