### ISSUE TITLE
Tag 3.0.0-wip Branch

### ISSUE THREAD

**Issue by greaterweb** [jlong/sass-bootstrap-defunct#94]
Is the 3.0.0-wip branch to ready to be tagged to match the 3.0.0 release? This would be useful for Bower.

Thanks!

**Comment by m5o** [comment]
Not finally, working on it

**Comment by m5o** [comment]
v3.0.0 tag is [here](https://github.com/jlong/sass-twitter-bootstrap/releases)

:sunrise:

**Comment by greaterweb** [comment]
Thank you!
