### ISSUE TITLE
Keep Separate copy of v.2.3.2

### ISSUE THREAD

**Issue by JadH** [jlong/sass-bootstrap-defunct#95]
It would be great if there is a copy of the v.2.3.2 available in a separate branch, same as the main bootstrap repo.
We are note yet using v.3.0.0 in our work.

**Comment by m5o** [comment]
All releases are tagged, you can access and download them via the [releases](https://github.com/jlong/sass-bootstrap/releases)

**Comment by JadH** [comment]
Great, well noted, thanks.
