### ISSUE TITLE
Encoding problem in '_grid.scss'

### ISSUE THREAD

**Issue by sudent** [jlong/sass-bootstrap-defunct#97]
When using compass, I've got `Line 79 of _grid.scss: Invalid US-ASCII character '\xE2'` and I've identified the problem to four occurrences of `—` within comments in that file. I've tried to set `@charset 'UTF-8'` but still the issues persist. In the end I just replaced the offending char with normal dash and it compiles fine afterwards.

Am I doing something wrong here or it's just my PC having the wrong settings? 

Thanks.

**Comment by m5o** [comment]
I don't know why there are so many `—` (mdash I guess) in the comments. Would be cool if you could submit this issue in the upstream repo.

From our Readme:

> Please do not submit issues or pull requests for issues with Bootstrap itself. Those should be pushed upstream in the Less version. [Please open a new issue](https://github.com/twbs/bootstrap/issues)

**Comment by sudent** [comment]
Closing this issue since it's something probably wrong with my environment or the way I'm compiling it instead. Tried using another tool to compile using the same PC and it works out fine. Will comment if I found the real culprit for future reference.
